<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <!-- changed to multi-target -->
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <UserSecretsId>176e78ba-2d90-49b3-b7c9-0ef2a477af82</UserSecretsId>
    </PropertyGroup>

    <!-- Ensure local .sqlite3 files are copied to build and publish output -->
    <ItemGroup>
        <Content Include="../db/anime-dimension.sqlite3">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>

    <!-- for debug build, include the local users.db  - ->
    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <Content Include="../db/users.db">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>
    -->

    <ItemGroup>
        <PackageReference Include="RestSharp" Version="113.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.2" />

        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
            <IncludeAssets>build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />
    </ItemGroup>

</Project>
